version: '3.4'

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: GateWay/Dockerfile
      ports:
        - "5001:80"

  orders:
    image: ${DOCKER_REGISTRY-}orders
    build:
      context: .
      dockerfile: Orders/Dockerfile
      ports:
        - "6001:80"


  payment:
    image: ${DOCKER_REGISTRY-}payment
    build:
      context: .
      dockerfile: Payment/Payment/Dockerfile
      ports:
        - "7001:80"


  user:
    image: ${DOCKER_REGISTRY-}user
    build:
      context: .
      dockerfile: User/Dockerfile
      ports:
        - "8001:80"

